# Proyecto
sonar.projectKey=aquipe99_springboot-devops-demo
sonar.organization=aquipe99

# Servidor
sonar.host.url=https://sonarcloud.io

# Código fuente
sonar.sources=src/main/java

# Tests
sonar.tests=src/test/java

# Reporte JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones de cobertura
sonar.coverage.exclusions=\
**/*Application.java,\
**/config/**,\
**/dto/**,\
**/entity/**,\
**/*MapperImpl.java,\
**/exception/**