spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/employee_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true